### ISSUE TITLE
[BUG] Segmentation Fault occurs in many requests for apache + mod_php/prefork

### ISSUE THREAD

**Issue by catatsuy** [DataDog/dd-trace-php#1055]
### Bug description

It happens occasionally (once a day or so) in a production environment where many requests are being served.

```
$ sudo gdb /usr/sbin/httpd core.httpd.9971 --command download/gdbinit-7.3
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-119.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/httpd...Reading symbols from /usr/lib/debug/usr/sbin/httpd.debug...done.
done.
[New LWP 9975]
[New LWP 9972]
[New LWP 9971]
[New LWP 9973]
[New LWP 9974]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/httpd -DFOREGROUND'.
Program terminated with signal 11, Segmentation fault.
#0  __GI_getenv (name=0x7fb42bd34b26 "l_proxy", name@entry=0x7fb42bd34b24 "all_proxy") at getenv.c:88
88                if (name_start == ep_start && !strncmp (*ep + 2, name, len)
(gdb) backtrace
#0  __GI_getenv (name=0x7fb42bd34b26 "l_proxy", name@entry=0x7fb42bd34b24 "all_proxy") at getenv.c:88
#1  0x00007fb42bd059f9 in GetEnv (variable=variable@entry=0x7fb42bd34b24 "all_proxy") at getenv.c:44
#2  curl_getenv (v=v@entry=0x7fb42bd34b24 "all_proxy") at getenv.c:52
#3  0x00007fb42bd03c17 in detect_proxy (conn=<optimized out>, conn=<optimized out>) at url.c:4147
#4  create_conn (async=0x7fb3cbffeb8c, in_connect=0x7fb3cbffeba4, data=0x7fb3c0020900) at url.c:5163
#5  Curl_connect (data=data@entry=0x7fb3c0020900, in_connect=in_connect@entry=0x7fb3c002c6b8, asyncp=asyncp@entry=0x7fb3cbffeb8c, protocol_done=protocol_done@entry=0x7fb3cbffeb8d) at url.c:5531
#6  0x00007fb42bd14780 in multi_runsingle (multi=multi@entry=0x7fb3c002c880, now=..., easy=easy@entry=0x7fb3c002c6a0) at multi.c:1045
#7  0x00007fb42bd15641 in curl_multi_perform (multi_handle=multi_handle@entry=0x7fb3c002c880, running_handles=running_handles@entry=0x7fb3cbffec80) at multi.c:1763
#8  0x00007fb42bd0c853 in curl_easy_perform (easy=0x7fb3c0020900) at easy.c:480
#9  0x00007fb41da460b4 in _dd_writer_loop () from /opt/datadog-php/extensions/ddtrace-20180731.so
#10 0x00007fb435c6bea5 in start_thread (arg=0x7fb3cbfff700) at pthread_create.c:307
#11 0x00007fb4357908dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

### PHP version

```
PHP 7.3.22 (cli) (built: Sep  1 2020 09:44:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.22, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.22, Copyright (c) 1999-2018, by Zend Technologies
    with ddtrace v0.49.0, Copyright Datadog, by Datadog
```

### Installed extensions

```
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
ddtrace
dom
exif
fileinfo
filter
ftp
gd
gettext
grpc
hash
iconv
igbinary
intl
json
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
ssh2
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
ddtrace
```

### OS info

CentOS Linux 7 (Core)

#### Output of phpinfo() (ddtrace >= 0.47.0)

```
$ php --ri=ddtrace

ddtrace


Datadog PHP tracer extension
For help, check out the documentation at https://docs.datadoghq.com/tracing/languages/php/
(c) Datadog 2020

Datadog tracing support => enabled
Version => 0.49.0
DATADOG TRACER CONFIGURATION => {"date":"2020-10-20T09:30:26Z","os_name":"Linux host 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64","os_version":"3.10.0-1127.19.1.el7.x86_64","version":"0.49.0","lang":"php","lang_version":"7.3.20","env":null,"enabled":true,"service":null,"enabled_cli":false,"agent_url":"http://localhost:8126","debug":false,"analytics_enabled":false,"sample_rate":1.000000,"sampling_rules":null,"tags":null,"service_mapping":null,"distributed_tracing_enabled":true,"priority_sampling_enabled":true,"dd_version":null,"architecture":"x86_64","sapi":"cli","ddtrace.request_init_hook":"/opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php","open_basedir_configured":false,"uri_fragment_regex":null,"uri_mapping_incoming":null,"uri_mapping_outgoing":null,"auto_flush_enabled":false,"generate_root_span":true,"http_client_split_by_domain":false,"measure_compile_time":true,"report_hostname_on_root_span":false,"traced_internal_functions":null,"auto_prepend_file_configured":false,"integrations_disabled":null,"enabled_from_env":true,"opcache.file_cache":null}

                               Diagnostics
Diagnostic checks => passed

Directive => Local Value => Master Value
ddtrace.disable => Off => Off
ddtrace.request_init_hook => /opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php => /opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php
```

**Comment by labbati** [comment]
Hi @catatsuy and thank you for the report. We will look immediately into it and get back to you as soon as possible.

**Comment by labbati** [comment]
One question I forgot to ask and that might help us with the investigation. Which exact version of curl package you have installed?

**Comment by catatsuy** [comment]
Thank you for your reply. Is the following information sufficient? @labbati 

```
$ php --ri=curl

curl

cURL support => enabled
cURL Information => 7.29.0
Age => 3
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => Yes
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => No
SSL => Yes
SSPI => No
TLS-SRP => No
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, scp, sftp, smtp, smtps, telnet, tftp
Host => x86_64-redhat-linux-gnu
SSL Version => NSS/3.44
ZLib Version => 1.2.7
libSSH Version => libssh2/1.8.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value
```

**Comment by labbati** [comment]
Yes, thank you

**Comment by morrisonlevi** [comment]
It looks like you are using Apache. Are you doing mod_php, prefork, or something else?

**Comment by catatsuy** [comment]
Yes. I am using Apache/2.4.6 (CentOS), mod_php and prefork. @morrisonlevi

**Comment by labbati** [comment]
Thank you for the info @catatsuy. We will try recreate the issue immediately and get back to you. I updated the title to reflect this specific environment.

**Comment by labbati** [comment]
Hi @catatsuy, I just wanted to let you know that we put under heavy load a configuration that it is in theory similar to your and we were not able to recreate any issue or segfault at all.

- Can you share your apache configuration specifically to php integration? E.g. any prefork/php config from your virtual host or apache conf?
- Can you share your exact opcache configuration? `php --ri 'Zend Opcache'`
- Can you describe your application? Any specific framework you are using?

**Comment by catatsuy** [comment]
Thank you for your investigation! @labbati 

I add the following settings to `/etc/httpd/conf/httpd.conf`.

```
LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
<IfModule prefork.c>
StartServers        144
MinSpareServers     144
MaxSpareServers     144
ServerLimit         256
MaxClients          144
MaxRequestsPerChild 10000
</IfModule>
```

```
$ php --ri 'Zend Opcache'

Zend OPcache

Opcode Caching => Disabled
Optimization => Disabled
SHM Cache => Enabled
File Cache => Disabled
Startup Failed => Opcode Caching is disabled for CLI

Directive => Local Value => Master Value
opcache.enable => On => On
opcache.use_cwd => On => On
opcache.validate_timestamps => On => On
opcache.validate_permission => Off => Off
opcache.validate_root => Off => Off
opcache.dups_fix => Off => Off
opcache.revalidate_path => Off => Off
opcache.log_verbosity_level => 2 => 2
opcache.memory_consumption => 1024 => 1024
opcache.interned_strings_buffer => 16 => 16
opcache.max_accelerated_files => 32530 => 32530
opcache.max_wasted_percentage => 30 => 30
opcache.consistency_checks => 0 => 0
opcache.force_restart_timeout => 180 => 180
opcache.revalidate_freq => 1 => 1
opcache.file_update_protection => 2 => 2
opcache.preferred_memory_model => no value => no value
opcache.blacklist_filename => /etc/php.d/opcache*.blacklist => /etc/php.d/opcache*.blacklist
opcache.max_file_size => 8388608 => 8388608
opcache.protect_memory => Off => Off
opcache.save_comments => On => On
opcache.optimization_level => 0x7FFEBFFF => 0x7FFEBFFF
opcache.opt_debug_level => 0 => 0
opcache.enable_file_override => On => On
opcache.enable_cli => Off => Off
opcache.error_log => no value => no value
opcache.restrict_api => no value => no value
opcache.lockfile_path => /tmp => /tmp
opcache.file_cache => no value => no value
opcache.file_cache_only => Off => Off
opcache.file_cache_consistency_checks => On => On
opcache.huge_code_pages => Off => Off
```

I use https://github.com/dietcake/dietcake and https://github.com/silexphp/Pimple etc. And I use [composer](https://getcomposer.org/)'s autoload.

Actually, I got many segmentation fault errors after application servers loaded `dd-trace-php`.
It is definitely caused by `dd-trace-php` because it does not occur on a server that does not load `dd-trace-php`.

But this is the only one I was able to get the `dd-trace-php` source code for on stacktrace.

I got many and various stacktrace (about 80 times per day) but I'll try to post some of them as appendix.

## Appendix

```
$ sudo gdb /usr/sbin/httpd core.httpd.18207 --command download/gdbinit-7.3
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-119.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/httpd...Reading symbols from /usr/lib/debug/usr/sbin/httpd.debug...done.
done.
[New LWP 18207]
[New LWP 18211]
[New LWP 18212]
[New LWP 18213]
[New LWP 18214]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/httpd -DFOREGROUND'.
Program terminated with signal 11, Segmentation fault.
#0  zend_hash_next_index_insert_new (ht=0x7fb42ccdecb0, pData=pData@entry=0x7ffd77bc4ff0) at /usr/src/debug/php-7.3.22/Zend/zend_hash.c:1019
1019    {
(gdb) backtrace
#0  zend_hash_next_index_insert_new (ht=0x7fb42ccdecb0, pData=pData@entry=0x7ffd77bc4ff0) at /usr/src/debug/php-7.3.22/Zend/zend_hash.c:1019
#1  0x00007fb42f35aff9 in php_explode (delim=0x7fb3d962f8b0, str=<optimized out>, return_value=return_value@entry=0x7fb42cc231e0, limit=9223372036854775807)
    at /usr/src/debug/php-7.3.22/ext/standard/string.c:1098
#2  0x00007fb42f35b7a5 in zif_explode (execute_data=0x7fb42cc23200, return_value=0x7fb42cc231e0) at /usr/src/debug/php-7.3.22/ext/standard/string.c:1184
#3  0x00007fb42f47fcf2 in ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.3.22/Zend/zend_vm_execute.h:694
#4  execute_ex (ex=0x7fb42ccdecb0) at /usr/src/debug/php-7.3.22/Zend/zend_vm_execute.h:55507
#5  0x00007fb42f484563 in zend_execute (op_array=op_array@entry=0x7fb42cc77000, return_value=0x0, return_value@entry=0x7fb3da47a2f8) at /usr/src/debug/php-7.3.22/Zend/zend_vm_execute.h:60939
#6  0x00007fb42f3f4d62 in zend_execute_scripts (type=type@entry=8, retval=0x7fb3da47a2f8, retval@entry=0x0, file_count=750924128, file_count@entry=3) at /usr/src/debug/php-7.3.22/Zend/zend.c:1568
#7  0x00007fb42f3949e0 in php_execute_script (primary_file=primary_file@entry=0x7ffd77bc7580) at /usr/src/debug/php-7.3.22/main/main.c:2637
#8  0x00007fb42f486782 in php_handler (r=<optimized out>) at /usr/src/debug/php-7.3.22/sapi/apache2handler/sapi_apache2.c:699
#9  0x000055d2413a0b80 in ap_run_handler (r=r@entry=0x55d242581e10) at config.c:169
#10 0x000055d2413a10c9 in ap_invoke_handler (r=r@entry=0x55d242581e10) at config.c:439
#11 0x000055d2413b503c in ap_internal_redirect (new_uri=<optimized out>, r=<optimized out>) at http_request.c:661
#12 0x00007fb42fa09e8c in handler_redirect (r=0x55d2427aa4d0) at mod_rewrite.c:5080
#13 0x000055d2413a0b80 in ap_run_handler (r=r@entry=0x55d2427aa4d0) at config.c:169
#14 0x000055d2413a10c9 in ap_invoke_handler (r=r@entry=0x55d2427aa4d0) at config.c:439
#15 0x000055d2413b5cda in ap_process_async_request (r=r@entry=0x55d2427aa4d0) at http_request.c:339
#16 0x000055d2413b5fc2 in ap_process_request (r=r@entry=0x55d2427aa4d0) at http_request.c:374
#17 0x000055d2413b2152 in ap_process_http_sync_connection (c=0x55d242578810) at http_core.c:190
#18 ap_process_http_connection (c=0x55d242578810) at http_core.c:231
#19 0x000055d2413aa1b0 in ap_run_process_connection (c=c@entry=0x55d242578810) at connection.c:41
#20 0x000055d2413aa598 in ap_process_connection (c=c@entry=0x55d242578810, csd=<optimized out>) at connection.c:202
#21 0x00007fb4350857ef in child_main (child_num_arg=child_num_arg@entry=104) at prefork.c:707
#22 0x00007fb435085a35 in make_child (s=0x55d2423350a0, slot=104) at prefork.c:810
#23 0x00007fb4350866ce in perform_idle_server_maintenance (p=<optimized out>) at prefork.c:912
#24 prefork_run (_pconf=<optimized out>, plog=<optimized out>, s=<optimized out>) at prefork.c:1100
#25 0x000055d24138512e in ap_run_mpm (pconf=pconf@entry=0x55d2422f6138, plog=0x55d242323358, s=0x55d2423350a0) at mpm_common.c:96
#26 0x000055d24137de86 in main (argc=2, argv=0x7ffd77bc7e08) at main.c:783
```

```
$ sudo gdb /usr/sbin/httpd /var/local/dumps/core.httpd.15630 --command download/gdbinit-7.3
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-119.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/httpd...Reading symbols from /usr/lib/debug/usr/sbin/httpd.debug...done.
done.
[New LWP 15630]
[New LWP 15669]
[New LWP 30499]
[New LWP 15668]
[New LWP 15667]
[New LWP 15670]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/httpd -DFOREGROUND'.
Program terminated with signal 11, Segmentation fault.
#0  zif_mb_convert_kana (execute_data=0x7fb96ce23270, return_value=0x7fb96ce23260) at /usr/src/debug/php-7.3.22/ext/mbstring/mbstring.c:3613
3613    {
(gdb) backtrace
#0  zif_mb_convert_kana (execute_data=0x7fb96ce23270, return_value=0x7fb96ce23260) at /usr/src/debug/php-7.3.22/ext/mbstring/mbstring.c:3613
#1  0x00007fb96f6b3cf2 in ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.3.22/Zend/zend_vm_execute.h:694
#2  execute_ex (ex=0x7fb96ce23270) at /usr/src/debug/php-7.3.22/Zend/zend_vm_execute.h:55507
#3  0x00007fb96f6b8563 in zend_execute (op_array=op_array@entry=0x7fb96ce661c0, return_value=0x0, return_value@entry=0x7fb91a7190b0) at /usr/src/debug/php-7.3.22/Zend/zend_vm_execute.h:60939
#4  0x00007fb96f628d62 in zend_execute_scripts (type=type@entry=8, retval=0x7fb91a7190b0, retval@entry=0x0, file_count=1826763264, file_count@entry=3) at /usr/src/debug/php-7.3.22/Zend/zend.c:1568
#5  0x00007fb96f5c89e0 in php_execute_script (primary_file=primary_file@entry=0x7ffeee191480) at /usr/src/debug/php-7.3.22/main/main.c:2637
#6  0x00007fb96f6ba782 in php_handler (r=<optimized out>) at /usr/src/debug/php-7.3.22/sapi/apache2handler/sapi_apache2.c:699
#7  0x0000558dfb55cb80 in ap_run_handler (r=r@entry=0x558dfc1e6070) at config.c:169
#8  0x0000558dfb55d0c9 in ap_invoke_handler (r=r@entry=0x558dfc1e6070) at config.c:439
#9  0x0000558dfb57103c in ap_internal_redirect (new_uri=<optimized out>, r=<optimized out>) at http_request.c:661
#10 0x00007fb96fc3de8c in handler_redirect (r=0x558dfc34c640) at mod_rewrite.c:5080
#11 0x0000558dfb55cb80 in ap_run_handler (r=r@entry=0x558dfc34c640) at config.c:169
#12 0x0000558dfb55d0c9 in ap_invoke_handler (r=r@entry=0x558dfc34c640) at config.c:439
#13 0x0000558dfb571cda in ap_process_async_request (r=r@entry=0x558dfc34c640) at http_request.c:339
#14 0x0000558dfb571fc2 in ap_process_request (r=r@entry=0x558dfc34c640) at http_request.c:374
#15 0x0000558dfb56e152 in ap_process_http_sync_connection (c=0x558dfc051a70) at http_core.c:190
#16 ap_process_http_connection (c=0x558dfc051a70) at http_core.c:231
#17 0x0000558dfb5661b0 in ap_run_process_connection (c=c@entry=0x558dfc051a70) at connection.c:41
#18 0x0000558dfb566598 in ap_process_connection (c=c@entry=0x558dfc051a70, csd=<optimized out>) at connection.c:202
#19 0x00007fb9752b97ef in child_main (child_num_arg=child_num_arg@entry=124) at prefork.c:707
#20 0x00007fb9752b9a35 in make_child (s=0x558dfbdff0a0, slot=124) at prefork.c:810
#21 0x00007fb9752ba6ce in perform_idle_server_maintenance (p=<optimized out>) at prefork.c:912
#22 prefork_run (_pconf=<optimized out>, plog=<optimized out>, s=<optimized out>) at prefork.c:1100
#23 0x0000558dfb54112e in ap_run_mpm (pconf=pconf@entry=0x558dfbdc0138, plog=0x558dfbded358, s=0x558dfbdff0a0) at mpm_common.c:96
#24 0x0000558dfb539e86 in main (argc=2, argv=0x7ffeee191d08) at main.c:783
```

```
$ sudo gdb /usr/sbin/httpd --core /var/local/dumps/core.httpd.15450 --command downloads/dd-trace-php-0.49.0/tooling/gdbinit-7.3
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-119.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/httpd...Reading symbols from /usr/lib/debug/usr/sbin/httpd.debug...done.
done.
[New LWP 15450]
[New LWP 15512]
[New LWP 15509]
[New LWP 15510]
[New LWP 5785]
[New LWP 15513]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/httpd -DFOREGROUND'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fb7ec99a9f8 in fast_memcpy (size=1856, src=0x7fb79a6bd340, dest=0x7fb7ecd61f80) at /usr/src/debug/php-7.3.23/ext/opcache/zend_accelerator_util_funcs.c:727
727             __asm__ volatile (
(gdb) backtrace
#0  0x00007fb7ec99a9f8 in fast_memcpy (size=1856, src=0x7fb79a6bd340, dest=0x7fb7ecd61f80) at /usr/src/debug/php-7.3.23/ext/opcache/zend_accelerator_util_funcs.c:727
#1  zend_accel_load_script (persistent_script=persistent_script@entry=0x7fb79a6bcc40, from_shared_memory=from_shared_memory@entry=1)
    at /usr/src/debug/php-7.3.23/ext/opcache/zend_accelerator_util_funcs.c:794
#2  0x00007fb7ec98d3d2 in persistent_compile_file (file_handle=<optimized out>, type=<optimized out>) at /usr/src/debug/php-7.3.23/ext/opcache/ZendAccelerator.c:2236
#3  0x00007fb7ef378ed3 in compile_filename (type=type@entry=2, filename=filename@entry=0x7fb7ecc23280) at Zend/zend_language_scanner.l:662
#4  0x00007fb7ef3f6f7d in zend_include_or_eval (inc_filename=0x7fb7ecc23280, type=2) at /usr/src/debug/php-7.3.23/Zend/zend_execute.c:3193
#5  0x00007fb7ef432568 in ZEND_INCLUDE_OR_EVAL_SPEC_CV_HANDLER () at /usr/src/debug/php-7.3.23/Zend/zend_vm_execute.h:37461
#6  0x00007fb7ef43792f in execute_ex (ex=0x7fb7ef7b84a0 <compiler_globals>) at /usr/src/debug/php-7.3.23/Zend/zend_vm_execute.h:59372
#7  0x00007fb7ef3a22e3 in zend_call_function (fci=fci@entry=0x7ffe9efb1100, fci_cache=<optimized out>, fci_cache@entry=0x7ffe9efb10e0) at /usr/src/debug/php-7.3.23/Zend/zend_execute_API.c:756
#8  0x00007fb7ef2a12eb in zif_spl_autoload_call (execute_data=<optimized out>, return_value=<optimized out>) at /usr/src/debug/php-7.3.23/ext/spl/php_spl.c:448
#9  0x00007fb7ef3a21ad in zend_call_function (fci=fci@entry=0x7ffe9efb12a0, fci_cache=<optimized out>, fci_cache@entry=0x7ffe9efb1280) at /usr/src/debug/php-7.3.23/Zend/zend_execute_API.c:770
#10 0x00007fb7ef3a28aa in zend_lookup_class_ex (name=name@entry=0x7fb79979f460, key=0x7fb79a5e1da0, use_autoload=use_autoload@entry=1) at /usr/src/debug/php-7.3.23/Zend/zend_execute_API.c:929
#11 0x00007fb7ef3a3268 in zend_fetch_class_by_name (class_name=0x7fb79979f460, key=<optimized out>, fetch_type=fetch_type@entry=512) at /usr/src/debug/php-7.3.23/Zend/zend_execute_API.c:1365
#12 0x00007fb7ef4300e7 in ZEND_INIT_STATIC_METHOD_CALL_SPEC_CONST_CONST_HANDLER () at /usr/src/debug/php-7.3.23/Zend/zend_vm_execute.h:5213
#13 0x00007fb7ef43900a in execute_ex (ex=0x7fb7ef7b84a0 <compiler_globals>) at /usr/src/debug/php-7.3.23/Zend/zend_vm_execute.h:56018
#14 0x00007fb7ef43f853 in zend_execute (op_array=op_array@entry=0x7fb7ecc79000, return_value=0x0, return_value@entry=0x7fb79a5f9380) at /usr/src/debug/php-7.3.23/Zend/zend_vm_execute.h:60944
#15 0x00007fb7ef3b0182 in zend_execute_scripts (type=type@entry=8, retval=0x7fb79a5f9380, retval@entry=0x0, file_count=-322817888, file_count@entry=3) at /usr/src/debug/php-7.3.23/Zend/zend.c:1568
#16 0x00007fb7ef34fce0 in php_execute_script (primary_file=primary_file@entry=0x7ffe9efb3850) at /usr/src/debug/php-7.3.23/main/main.c:2637
#17 0x00007fb7ef441a72 in php_handler (r=<optimized out>) at /usr/src/debug/php-7.3.23/sapi/apache2handler/sapi_apache2.c:699
#18 0x0000557563a3db80 in ap_run_handler (r=r@entry=0x557564bf3328) at config.c:169
#19 0x0000557563a3e0c9 in ap_invoke_handler (r=r@entry=0x557564bf3328) at config.c:439
#20 0x0000557563a5203c in ap_internal_redirect (new_uri=<optimized out>, r=<optimized out>) at http_request.c:661
#21 0x00007fb7ef9c4e8c in handler_redirect (r=0x557564995af0) at mod_rewrite.c:5080
#22 0x0000557563a3db80 in ap_run_handler (r=r@entry=0x557564995af0) at config.c:169
#23 0x0000557563a3e0c9 in ap_invoke_handler (r=r@entry=0x557564995af0) at config.c:439
#24 0x0000557563a52cda in ap_process_async_request (r=r@entry=0x557564995af0) at http_request.c:339
#25 0x0000557563a52fc2 in ap_process_request (r=r@entry=0x557564995af0) at http_request.c:374
#26 0x0000557563a4f152 in ap_process_http_sync_connection (c=0x5575649b3510) at http_core.c:190
#27 ap_process_http_connection (c=0x5575649b3510) at http_core.c:231
#28 0x0000557563a471b0 in ap_run_process_connection (c=c@entry=0x5575649b3510) at connection.c:41
#29 0x0000557563a47598 in ap_process_connection (c=c@entry=0x5575649b3510, csd=<optimized out>) at connection.c:202
#30 0x00007fb7f50407ef in child_main (child_num_arg=child_num_arg@entry=22) at prefork.c:707
#31 0x00007fb7f5040a35 in make_child (s=0x55756475c8a0, slot=22) at prefork.c:810
#32 0x00007fb7f50416ce in perform_idle_server_maintenance (p=<optimized out>) at prefork.c:912
#33 prefork_run (_pconf=<optimized out>, plog=<optimized out>, s=<optimized out>) at prefork.c:1100
#34 0x0000557563a2212e in ap_run_mpm (pconf=pconf@entry=0x55756471a138, plog=0x557564747358, s=0x55756475c8a0) at mpm_common.c:96
#35 0x0000557563a1ae86 in main (argc=2, argv=0x7ffe9efb40d8) at main.c:783
```

**Comment by labbati** [comment]
Thank you @catatsuy for the additional detail.

**Comment by labbati** [comment]
@catatsuy just a quick update, we put under load a sample app using your configuration with no luck. Zero segfaults generated.

Any possibility you can share the actual core dumps that you posted above so we can inspect them closer? If you can please create a ticket and you will receive steps to upload large files.

**Comment by catatsuy** [comment]
@labbati Sorry. I cannot share the actual core dumps to you because of security issue.

**Comment by labbati** [comment]
Hi @catatsuy just a quick comment. We made new attempts under load using a heavy Symphony app and your very same configuration. Unfortunately we are not able yet to recreate your issue. All the tests so far seems to show that everything works correctly.

If you share the org name (you can also reach out to me on our public datadoghq.slack.com slack channel at the handle @luca.abbati), I can have a CSM reaching out to you. Maybe we can setup a debug session. We have a variety of options, including all interactions will be covered by NDA.

Otherwise I see no other option, unfortunately, than closing this issue as we cannot reproduce it.

**Comment by labbati** [comment]
Hi @catatsuy. Do you think we can schedule a call so we can together try to isolate you issue to one specific functionality?
In order to succeed, we will need access to an environment (preferably a staging or testing environment) where we can change settings and restart apache. Moreover, we need to have a decent frequency of errors, meaning that when we change configuration (after a restart) we should be able to observe a SEGFAULT in minutes, so we can call a state 'working' or 'broken'.

Let me know if that is possible.

**Comment by catatsuy** [comment]
Sorry for the late reply. @labbati 

The coredump file contains sensitive information and cannot be shared.

However, if I can get the coredump file in the development environment, I might be able to provide it.

I will build an environment to get coredumps in the development environment. If I can get it, I would like to discuss it with you.

**Comment by labbati** [comment]
Thank you, that would be very useful.

**Comment by irabinovitch** [comment]
@catatsuy I was hoping to circle back and see if you'd had a chance to replicate the issue in your dev environment. Alternatively if you prefer to share the existing file confidentially in a support ticket we can help follow up there rather than in public issues.

**Comment by catatsuy** [comment]
The other day, I made it possible to get coredump in the development environment as well. But I haven't got it yet.

It only happens about once a day per server in the production environment, so it will take some time.

When I are able to get it, I would like to proceed with support confidentially. Is there a recommended procedure for doing so?

**Comment by labbati** [comment]
Thank you @catatsuy

**Comment by labbati** [comment]
I am closing this issue as we are not able to proceed with the investigation without a core dump. In case we are able to retrieve it please reach out to our support team: https://www.datadoghq.com/support/
