### ISSUE TITLE
[BUG][0.85.0] SIGSEGV using #[DDTrace\Trace] attribute

### ISSUE THREAD

**Issue by Majkl578** [DataDog/dd-trace-php#1978]
### Bug description

Trying to use `#[\DDTrace\Trace]` attribute on a PHP method crashes PHP FPM with SIGSEGV.

Backtrace:
```
(gdb) bt
#0  0x00007f935de32f6b in zai_interceptor_replace_observer_current (func=0x44c56cd0, remove=false) at /home/circleci/datadog/tmp/build_extension/zend_abstract_interface/interceptor/php8/interceptor.c:502
#1  0x00007f935de38cdd in zai_hook_resolved_ensure_hooks_entry (resolved=0x44c56cd0, resolved@entry=0x7f935c9fe900) at /home/circleci/datadog/tmp/build_extension/zend_abstract_interface/hook/hook.c:355
#2  zai_hook_resolved_install (hook=hook@entry=0x7f935c674150, resolved=resolved@entry=0x44c56cd0) at /home/circleci/datadog/tmp/build_extension/zend_abstract_interface/hook/hook.c:395
#3  0x00007f935de3b4a2 in zai_hook_install_resolved_generator (function=function@entry=0x44c56cd0, begin=begin@entry=0x7f935de4aa60 <dd_uhook_begin>, resumption=resumption@entry=0x7f935de4a2f0 <dd_uhook_generator_resumption>, 
    yield=yield@entry=0x7f935de4a5c0 <dd_uhook_generator_yield>, end=end@entry=0x7f935de4a420 <dd_uhook_end>, aux=..., dynamic=dynamic@entry=16) at /home/circleci/datadog/tmp/build_extension/zend_abstract_interface/hook/hook.c:996
#4  0x00007f935de49a94 in dd_uhook_on_function_resolve (func=0x44c56cd0) at /home/circleci/datadog/tmp/build_extension/ext/hook/uhook_attributes.c:405
#5  0x00007f935de3a389 in zai_hook_resolve_class (ce=ce@entry=0x44c56878, lcname=<optimized out>) at /home/circleci/datadog/tmp/build_extension/zend_abstract_interface/hook/hook.c:654
#6  0x00007f935de33f72 in zai_interceptor_add_new_entries (classpos=<optimized out>, funcpos=<optimized out>) at /home/circleci/datadog/tmp/build_extension/zend_abstract_interface/interceptor/php8/resolver_pre-8_2.c:16
#7  0x00007f935de340ed in zai_interceptor_compile_file (file_handle=<optimized out>, type=2) at /home/circleci/datadog/tmp/build_extension/zend_abstract_interface/interceptor/php8/resolver_pre-8_2.c:41
#8  0x0000557e673676d9 in compile_filename (type=type@entry=2, filename=filename@entry=0x415f3330) at ./Zend/zend_language_scanner.c:707
#9  0x0000557e673d768a in zend_include_or_eval (inc_filename_zv=<optimized out>, type=2) at ./Zend/zend_execute.c:4843
#10 0x0000557e673e4185 in ZEND_INCLUDE_OR_EVAL_SPEC_OBSERVER_HANDLER () at ./Zend/zend_vm_execute.h:4939
#11 0x0000557e6740ac2d in execute_ex (ex=0x44c56cd0) at ./Zend/zend_vm_execute.h:56192
#12 0x0000557e67396fa4 in zend_call_function (fci=<optimized out>, fci_cache=<optimized out>) at ./Zend/zend_execute_API.c:912
#13 0x0000557e673973c5 in zend_call_known_function (fn=0x41c9c7f0, object=<optimized out>, called_scope=<optimized out>, retval_ptr=retval_ptr@entry=0x0, param_count=param_count@entry=1, params=params@entry=0x7ffeb95f3550, 
    named_params=0x0) at ./Zend/zend_execute_API.c:1001
#14 0x0000557e6729a950 in spl_perform_autoload (class_name=0x415f32d8, lc_name=0x44c53f28) at ./ext/spl/php_spl.c:446
#15 0x0000557e6739627c in zend_lookup_class_ex (name=name@entry=0x415f32d8, key=0x44c53f28, flags=flags@entry=512) at ./Zend/zend_execute_API.c:1145
#16 0x0000557e67397712 in zend_fetch_class_by_name (class_name=0x415f32d8, key=<optimized out>, fetch_type=fetch_type@entry=512) at ./Zend/zend_execute_API.c:1605
#17 0x0000557e673e1a5f in ZEND_NEW_SPEC_CONST_UNUSED_HANDLER () at ./Zend/zend_vm_execute.h:10167
#18 0x0000557e6740ade4 in execute_ex (ex=0x44c56cd0) at ./Zend/zend_vm_execute.h:56684
#19 0x0000557e67413bbd in zend_execute (op_array=0x7f9362c02400, return_value=0x0) at ./Zend/zend_vm_execute.h:60151
#20 0x0000557e673a57cd in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at ./Zend/zend.c:1799
#21 0x0000557e67340f61 in php_execute_script (primary_file=primary_file@entry=0x7ffeb95f5ca0) at ./main/main.c:2542
#22 0x0000557e671ebd3e in main (argc=<optimized out>, argv=<optimized out>) at ./sapi/fpm/fpm/fpm_main.c:1919
```

### PHP version
```
# php-fpm8.1 -v
PHP 8.1.17 (fpm-fcgi) (built: Mar 16 2023 14:37:38)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.17, Copyright (c), by Zend Technologies
    with ddtrace v0.85.0, Copyright Datadog, by Datadog
    with datadog-profiling v0.14.0, Copyright Datadog, by Datadog
    with ddappsec v0.6.0, Copyright Datadog, by Datadog
```

### Tracer version
0.85.0

### Installed extensions
```
[PHP Modules]
amqp
bcmath
calendar
Core
ctype
curl
datadog-profiling
date
ddappsec
ddtrace
decimal
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
intl
json
libxml
mbstring
memcached
msgpack
openssl
pcntl
pcre
PDO
pdo_pgsql
pgsql
Phar
posix
raphf
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
uuid
xml
xmlreader
xmlwriter
xsl
yaml
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
datadog-profiling
ddappsec
ddtrace
```

### OS info
Debian bullseye-based Docker image (PHP from packages.sury.org)

#### Output of phpinfo()
```
{ "date": "2023-03-17T12:14:24Z", "os_name": "Linux b768be466f6f 6.1.0-6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.15-1 (2023-03-05) x86_64", "os_version": "6.1.0-6-amd64", "version": "0.85.0", "lang": "php", "lang_version": "8.1.15", "env": "dev", "enabled": true, "service": "mailwise-backend", "enabled_cli": false, "agent_url": "http:\/\/datadog-agent:8126", "debug": true, "analytics_enabled": false, "sample_rate": 1, "sampling_rules": [], "tags": [], "service_mapping": { "pdo": "mailwise-backend-db", "phpredis": "mailwise-backend-redis", "elasticsearch": "mailwise-backend-elasticsearch" }, "distributed_tracing_enabled": true, "priority_sampling_enabled": true, "dd_version": null, "architecture": "x86_64", "sapi": "fpm-fcgi", "datadog.trace.request_init_hook": "\/opt\/datadog\/dd-library\/0.85.0\/dd-trace-sources\/bridge\/dd_wrap_autoloader.php", "open_basedir_configured": false, "uri_fragment_regex": null, "uri_mapping_incoming": null, "uri_mapping_outgoing": null, "auto_flush_enabled": false, "generate_root_span": true, "http_client_split_by_domain": false, "measure_compile_time": false, "report_hostname_on_root_span": false, "traced_internal_functions": null, "auto_prepend_file_configured": false, "integrations_disabled": "default", "enabled_from_env": true, "opcache.file_cache": null } 
```

```
Diagnostic checks | passed
```

**Comment by elvecz** [comment]
+1

**Comment by bwoebi** [comment]
Hey @Majkl578,

Thanks for the information about opcache, I think we're not currently testing them together with opcache. I'll verify and come back to you.

**Comment by bwoebi** [comment]
Hmm @Majkl578,

I've been trying to reproduce that issue for a while, but I've been failing to. Is there something specific with the methods you're overloading, the overloaded class etc.?

**Comment by bwoebi** [comment]
I've been trying many things, but what I ended up is https://github.com/DataDog/dd-trace-php/commit/da3dd58d68db2aa346d893a95395bc747ab3214a#diff-16e64fec7cb0fb6120bc6eeeb55af61856620422b3efe30f6dbc3ad49e37521d in my test. Does that simple thing also crash for you, or does it require a more complex reproducer?

**Comment by bwoebi** [comment]
@Majkl578 Is this still relevant to you?

**Comment by pierotibou** [comment]
Hello @Majkl578 , we'll close this one as we haven't heard from you. Do not hesitate to reopen it if you're still facing the issue obviously.
