### ISSUE TITLE
[BUG] Multiple unique TypeError's are being grouped as the same and have the same fingerprint

### ISSUE THREAD

**Issue by Noojuno** [DataDog/dd-trace-php#2106]
### Bug description
Multiple TypeError's are being grouped under the same fingerprint in error tracking, despite coming from different files and having different stack traces. There have been no manual changes to the fingerprint, these are all automatically generated.

A few examples of the stack traces being grouped together:
```
TypeError: Uncaught TypeError (HTTP/1.0 500 Internal Server Error): Argument 2 passed to <redacted>\Framework\Classes\Formatting::renderFileContents() must be of the type array, null given, called in /var/code/<redacted>/master/releases/2023-06-15_09-18-53/public/modules/dashboard/memo/form.php on line 36 in /var/code/<redacted>/master/releases/2023-06-15_09-18-53/framework/Classes/Formatting.php:956
#0 /var/code/<redacted>/master/releases/2023-06-15_09-18-53/public/modules/dashboard/memo/form.php(36): <redacted>\Framework\Classes\Formatting::renderFileContents()
#1 /var/code/<redacted>/master/releases/2023-06-15_09-18-53/module/Common/src/FileReader/FileReader.php(105): require()
#2 /var/code/<redacted>/master/releases/2023-06-15_09-18-53/module/Common/src/FileReader/FileReader.php(77): Common\FileReader\FileReader->requireContents()
#3 /var/code/<redacted>/master/releases/2023-06-15_09-18-53/module/Common/src/FileReader/FileReader.php(57): Common\FileReader\FileReader->renderContents()
#4 /var/code/<redacted>/master/releases/2023-06-15_09-18-53/framework/Classes/Formatting.php(943): Common\FileReader\FileReader->getContents()
#5 /var/code/<redacted>/master/releases/2023-06-15_09-18-53/framework/Classes/FrameworkDataItem.php(1488): <redacted>\Framework\Classes\Formatting::getFileContents()
#6 /var/code/<redacted>/master/releases/2023-06-15_09-18-53/framework/Classes/RecordPopup.php(25): <redacted>\Framework\Classes\FrameworkDataItem->getForm()
#7 /var/code/<redacted>/master/releases/2023-06-15_09-18-53/framework/Controllers/GeneralController.php(349): <redacted>\Framework\Classes\RecordPopup->__construct()
#8 /var/code/<redacted>/master/releases/2023-06-15_09-18-53/framework/Controllers/BaseController.php(76): <redacted>\Framework\Controllers\GeneralController->actionOpenPopupRecord()
#9 /var/code/<redacted>/master/releases/2023-06-15_09-18-53/framework/Controllers/BaseController.php(96): <redacted>\Framework\Controllers\BaseController->_execute()
#10 /var/code/<redacted>/master/releases/2023-06-15_09-18-53/module/Common/src/Controllers/RequestRunner.php(61): <redacted>\Framework\Controllers\BaseController->execute()
#11 /var/code/<redacted>/master/releases/2023-06-15_09-18-53/public/controller.php(45): Common\Controllers\RequestRunner->run()
#12 {main}
```
```
TypeError: Uncaught TypeError (HTTP/1.0 500 Internal Server Error): Argument 6 passed to LineAdjustmentFramework\Dto\AppliableLineAdjustmentSearchDto::__construct() must be of the type int, null given, called in /var/code/<redacted>/release/37.6/releases/2023-06-15_19-31-51/module/LineAdjustmentFramework/src/Mapper/AppliableLineAdjustmentSearchMapper.php on line 50 in /var/code/<redacted>/release/37.6/releases/2023-06-15_19-31-51/module/LineAdjustmentFramework/src/Dto/AppliableLineAdjustmentSearchDto.php:125
#0 /var/code/<redacted>/release/37.6/releases/2023-06-15_19-31-51/module/LineAdjustmentFramework/src/Mapper/AppliableLineAdjustmentSearchMapper.php(50): LineAdjustmentFramework\Dto\AppliableLineAdjustmentSearchDto->__construct()
#1 /var/code/<redacted>/release/37.6/releases/2023-06-15_19-31-51/framework/Controllers/FinancialController.php(450): LineAdjustmentFramework\Mapper\AppliableLineAdjustmentSearchMapper->map()
#2 /var/code/<redacted>/release/37.6/releases/2023-06-15_19-31-51/framework/Controllers/BaseController.php(106): <redacted>\Framework\Controllers\FinancialController->actionGetAvailableAdjustments()
#3 /var/code/<redacted>/release/37.6/releases/2023-06-15_19-31-51/framework/Controllers/BaseController.php(131): <redacted>\Framework\Controllers\BaseController->_execute()
#4 /var/code/<redacted>/release/37.6/releases/2023-06-15_19-31-51/framework/Classes/<redacted>.php(63): <redacted>\Framework\Controllers\BaseController->execute()
#5 /var/code/<redacted>/release/37.6/releases/2023-06-15_19-31-51/public/controller.php(39): <redacted>\Framework\Classes\<redacted>::run()
#6 {main}
```
Both of these are being collected under the same fingerprint, `v2.0DF45D9F101D32D0BE5121DA03F96481`. There are at least 4 other TypeError's that are being grouped under the same fingerprint. 

### PHP version
PHP 7.4.33

### Tracer version
0.88.0

### Installed extensions
```
[PHP Modules]
bcmath
blackfire
calendar
Core
ctype
curl
date
ddappsec
ddtrace
dom
exif
FFI
fileinfo
filter
ftp
gd
geoip
gettext
hash
iconv
igbinary
imagick
imap
json
libxml
mbstring
mysqli
mysqlnd
newrelic
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
blackfire
ddappsec
ddtrace
```

### OS info
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy

#### Output of phpinfo() (ddtrace >= 0.47.0)
```json
{ "date": "2023-06-16T04:59:06Z", "os_name": "Linux ip-10-80-33-15 5.19.0-1024-aws #25~22.04.1-Ubuntu SMP Tue Apr 18 23:41:58 UTC 2023 x86_64", "os_version": "5.19.0-1024-aws", "version": "0.87.2", "lang": "php", "lang_version": "7.4.33", "env": null, "enabled": true, "service": null, "enabled_cli": false, "agent_url": "http:\/\/localhost:8126", "debug": false, "analytics_enabled": false, "sample_rate": 1, "sampling_rules": [], "tags": [], "service_mapping": [], "distributed_tracing_enabled": true, "priority_sampling_enabled": true, "dd_version": null, "architecture": "x86_64", "sapi": "fpm-fcgi", "datadog.trace.request_init_hook": "\/opt\/datadog\/dd-library\/0.87.2\/dd-trace-sources\/bridge\/dd_wrap_autoloader.php", "open_basedir_configured": false, "uri_fragment_regex": null, "uri_mapping_incoming": null, "uri_mapping_outgoing": null, "auto_flush_enabled": false, "generate_root_span": true, "http_client_split_by_domain": false, "measure_compile_time": true, "report_hostname_on_root_span": false, "traced_internal_functions": null, "auto_prepend_file_configured": false, "integrations_disabled": "default", "enabled_from_env": true, "opcache.file_cache": null }
```

Diagnostics
--
Diagnostic checks | passed

**Comment by bwoebi** [comment]
Hey @Noojuno,

I've talked to our error tracking team, they are aware of the issue (ignoring the stacktraces on their end), but haven't fixed it yet.
Please talk to the datadog support, if you want to raise priority of the issue, or be updated as soon as the issue is fixed. 

These github issues are generally just dealing for tracer and profiling specific issues.
Thanks for your understanding.
