### ISSUE TITLE
[BUG] Composer Package 0.45.1 is not working with Extension Version. 0.45.1

### ISSUE THREAD

**Issue by Bibob7** [DataDog/dd-trace-php#888]
**Describe the bug**
If I install extension version 0.45.1 and php composer package version 0.45.1, It tells me that it can not find some dd_trace functions like ddtrace_config_debug_enabled() or ddtrace_config_global_tags()
```
Fatal error: Uncaught Error: Call to undefined function ddtrace_config_global_tags() in /application/vendor/datadog/dd-trace/src/DDTrace/Tracer.php:117
Stack trace:
#0 /application/vendor/datadog/dd-trace/src/DDTrace/Bootstrap.php(98): DDTrace\Tracer->__construct()
#1 /application/vendor/datadog/dd-trace/src/DDTrace/Bootstrap.php(30): DDTrace\Bootstrap::resetTracer()
#2 /opt/datadog-php/dd-trace-sources/bridge/dd_init.php(16): DDTrace\Bootstrap::tracerOnce()
#3 /opt/datadog-php/dd-trace-sources/bridge/functions.php(119): require('/opt/datadog-ph...')
#4 /application/vendor/composer/ClassLoader.php(302): Composer\Autoload\ClassLoader::dd_trace_callback(Array, true, true)
#5 /application/vendor/composer/autoload_real.php(51): Composer\Autoload\ClassLoader->register(true)
#6 /application/vendor/autoload.php(12): ComposerAutoloaderInit966074e503a9b93cfbaad35de4edef50::getLoader()
#7 /application/config/bootstrap.php(5): require('/application/ve...')
#8 /application/roadrunner/test.php(5): require('/application/co...')
#9 {mai in /application/vendor/datadog/dd-trace/src/DDTrace/Tracer.php on line 117
```

**PHP Info**
- Output of `php -v`
```
PHP 7.4.3 (cli) (built: Feb 20 2020 21:45:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with ddtrace v0.45.1, Copyright Datadog, by Datadog
    with blackfire v1.30.0~linux-musl-x64-non_zts74, https://blackfire.io, by Blackfire
```

- Output of `php -m`
```
[PHP Modules]
blackfire
Core
ctype
curl
date
ddtrace
dom
fileinfo
filter
ftp
grpc
hash
iconv
json
libxml
mbstring
mongodb
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
protobuf
rdkafka
readline
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib

[Zend Modules]
blackfire
ddtrace
```

**OS Info**
- Output of `cat /etc/os-release | grep -E "(NAME)|(VERSION)"`
```
NAME="Alpine Linux"
VERSION_ID=3.11.3
PRETTY_NAME="Alpine Linux v3.11"
```

**Output of dd-doctor**
(I adjusted dd-doctor-php file to see the missing functions:
```
#WARNING: Script is running from the CLI SAPI.
         Please run this script from your web browser.

DataDog trace extension verification

- PHP version and SAPI                               [7.4.3 - cli]
- ddtrace extension installed                        [OK]
- ddtrace version (installed)                        [0.45.1]
- ddtrace version (const)                            [0.45.1]
- ddtrace version (userland)                         [0.45.1]
- ddtrace versions in sync                           [OK]
- dd_trace() function available                      [OK]
- ddtrace_config_debug_enabled() function available  [FAIL]
- ddtrace_config_global_tags() function available    [FAIL]
- dd_trace_env_config() function available           [OK]
- ddtrace.request_init_hook set                      [OK]
- ddtrace.request_init_hook reachable                [OK]
- ddtrace.request_init_hook has run                  [OK]
- 'open_basedir' allows access to '/proc/self/'      [OK]
- IntegrationsLoader exists                          [OK]
- Integrations not loaded yet                        [OK]
- Registering an autoloader...
- Integrations loaded                                [OK]
- DDTrace\Tracer class exists                        [OK]
- Background sender is enabled?                      [NO]
  > You can enable the background sender via
    DD_TRACE_BETA_SEND_TRACES_VIA_THREAD=true
- Opcache enabled:                                   [NO]
- Opcache enabled:                                   [YES]

```

**If you are upgrading**

With composer  package 0.44.1 and extension version 0.45.1, it is working.

**Comment by labbati** [comment]
Thanks for reporting, looking into it right now

**Comment by labbati** [comment]
Hi @Bibob7 I was able to reproduce the issue and I opened a PR that fixes it #889. You can find more details in the PR.

**Scope**: this bug occurs when users are doing manual instrumentation the datadog api. Users only relying on automatic instrumentation and users doing manual instrumentation via the OpenTracing api are NOT impacted.

We are about to release it as a patch 0.45.2 release. But if the meantime you have a testing env to confirm that the fix works for you it would be great:
- [deb](https://github.com/DataDog/dd-trace-php/releases/download/0.45.1/datadog-php-tracer_0.45.1_amd64.deb)
- [rpm](https://158220-119990860-gh.circle-artifacts.com/0/datadog-php-tracer-1.0.0_nightly-1.x86_64.rpm)
- [apk](https://158220-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_1.0.0-nightly_noarch.apk)
- [tar.gz](https://158220-119990860-gh.circle-artifacts.com/0/datadog-php-tracer-1.0.0-nightly.x86_64.tar.gz)

**Comment by Bibob7** [comment]
Unfortunately, I still have the same problem. Here is the output of dd-doctor.php:
```
WARNING: Script is running from the CLI SAPI.
         Please run this script from your web browser.

DataDog trace extension verification

- PHP version and SAPI                               [7.4.3 - cli]
- ddtrace extension installed                        [OK]
- ddtrace version (installed)                        [1.0.0-nightly]
- ddtrace version (const)                            [1.0.0-nightly]
- ddtrace version (userland)                         [1.0.0-nightly]
- ddtrace versions in sync                           [OK]
- dd_trace() function available                      [OK]
- ddtrace_config_debug_enabled() function available  [FAIL]
- ddtrace_config_global_tags() function available    [FAIL]
- dd_trace_env_config() function available           [OK]
- ddtrace.request_init_hook set                      [OK]
- ddtrace.request_init_hook reachable                [OK]
- ddtrace.request_init_hook has run                  [OK]
- 'open_basedir' allows access to '/proc/self/'      [OK]
- IntegrationsLoader exists                          [OK]
- Integrations not loaded yet                        [OK]
- Registering an autoloader...
- Integrations loaded                                [OK]
- DDTrace\Tracer class exists                        [OK]
- Background sender is enabled?                      [NO]
  > You can enable the background sender via
    DD_TRACE_BETA_SEND_TRACES_VIA_THREAD=true
- Opcache enabled:                                   [NO]
- Opcache enabled:                                   [YES]
```

I tested it with composer package version 0.45.1
Is this correct?

**Comment by labbati** [comment]
@Bibob7 not sure how those values are extracted in the modified version of `dd-doctor.php`. My advice is to installe [0.45.2](https://github.com/DataDog/dd-trace-php/releases/tag/0.45.2) that we just released with this hot fix and install that. In any case, I was able to replicate your exact error with the previous version so I am confident your issue is gone.

**Comment by labbati** [comment]
Hi @Bibob7 I am closing this issue as we were able to reproduce it and fix in our latest release.
Thanks for taking the time to report it. Feel free to reopen it if you still see the issue.
