### ISSUE TITLE
[BUG] Segfaults with opcache.file_cache reused between FPM and CLI

### ISSUE THREAD

**Issue by Majkl578** [DataDog/dd-trace-php#902]
Hello,

**Describe the bug**
We're currently seeing segmentation faults with OPcache file cache being reused between FPM and CLI. This only happens with `ddtrace` extension loaded and under specific conditions. So far I've been able to trigger the bug with preoading enabled, then hitting a PHP script through HTTP, then running `php -m` immediately segfaults.

I was able to obtain a backtrace from a dumped core, although it doesn't seem to be particularly verbose:
```
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00005592b8130aa9 in ZEND_USER_OPCODE_SPEC_HANDLER () at ./Zend/zend_vm_execute.h:2637
        ret = <optimized out>
#2  0x00005592b813262d in execute_ex (ex=0x7f1541e12020) at ./Zend/zend_vm_execute.h:53902
        orig_opline = <optimized out>
        orig_execute_data = <optimized out>
#3  0x00005592b8139981 in zend_execute (op_array=0x7f1541e66000, return_value=<optimized out>) at ./Zend/zend_vm_execute.h:57922
        execute_data = 0x7f1541e12020
        object_or_called_scope = <optimized out>
        call_info = <optimized out>
#4  0x00007f153e7b3a85 in dd_execute_php_file () from /opt/datadog-php/extensions/ddtrace-20190902.so
No symbol table info available.
#5  0x00007f153e7a4540 in zm_activate_ddtrace () from /opt/datadog-php/extensions/ddtrace-20190902.so
No symbol table info available.
#6  0x00005592b80b8350 in zend_activate_modules () at ./Zend/zend_API.c:2605
        module = 0x5592ba2bf890
        p = 0x5592ba512b00
#7  0x00005592b80513d6 in php_request_startup () at ./main/main.c:1834
        __orig_bailout = 0x7ffe88a47a50
        __bailout = {{__jmpbuf = {94088643238464, 8335647263630806343, 140731190900884, 2, 94088676743600, 140731190905828, 8335647263828987207, 2843541885642460487}, __mask_was_saved = 0, __saved_mask = {__val = {1, 0, 1, 140731190901520, 94088641163538, 
                140731190900736, 94088643238464, 140731190901512, 140731190900736, 0, 94085553586178, 2, 140731190900888, 0, 94088643238464, 140731190900888}}}}
        retval = 0
#8  0x00005592b813aebd in do_cli (argc=2, argv=0x5592ba2799b0) at ./sapi/cli/php_cli.c:676
        __orig_bailout = 0x7ffe88a48bf0
        __bailout = {{__jmpbuf = {0, -8335254381459157689, 0, 0, 140731190905832, 140731190905828, 8335647263615077703, 2843542034120691015}, __mask_was_saved = 0, __saved_mask = {__val = {94088642179348, 94088642179372, 94088642082117, 94088642082138, 94088642179385, 
                94088642179405, 94088642179422, 94088642179443, 94088642179453, 94088642179467, 94088642179489, 94088642179508, 94088642179535, 94088642179564, 0, 7955998172649846063}}}}
        c = <optimized out>
        file_handle = {handle = {fp = 0x0, stream = {handle = 0x0, isatty = 0, reader = 0x0, fsizer = 0x0, closer = 0x0}}, filename = 0x0, opened_path = 0x0, type = ZEND_HANDLE_FILENAME, free_filename = 0 '\000', buf = 0x0, len = 0}
        behavior = 1
        reflection_what = 0x0
        request_started = 0
        exit_status = 0
        php_optarg = 0x0
        php_optind = 2
        exec_direct = 0x0
        exec_run = 0x0
        exec_begin = 0x0
        exec_end = 0x0
        arg_free = 0x0
        arg_excp = <synthetic pointer>
        script_file = 0x0
        translated_path = 0x0
        param_error = 0x0
        hide_argv = 0
#9  0x00005592b7f1a99b in main (argc=2, argv=0x5592ba2799b0) at ./sapi/cli/php_cli.c:1356
        __orig_bailout = 0x0
        __bailout = {{__jmpbuf = {94088643302912, -8335254381459157689, 0, 0, 140731190905832, 140731190905828, 8335647257805966663, 2843554420705709383}, __mask_was_saved = 0, __saved_mask = {__val = {139729316092992, 37, 139729314812617, 576, 0, 72704, 0, 7, 0, 121, 
                94088676703752, 72703, 72752, 18446744073709550968, 1136, 5085241283009}}}}
        c = <optimized out>
        exit_status = 0
        module_started = 1
        sapi_started = 1
        php_optarg = 0x0
        php_optind = 2
        use_extended_info = 0
        ini_path_override = 0x0
        ini_entries = 0x5592ba279c50 "html_errors=0\nregister_argc_argv=1\nimplicit_flush=1\noutput_buffering=0\nmax_execution_time=0\nmax_input_time=-1\n"
        ini_entries_len = 0
        ini_ignore = 0
        sapi_module = <optimized out>
```

**PHP Info**
- Output of `php -v`
```
PHP 7.4.6 (cli) (built: May 14 2020 10:03:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies
    with blackfire v1.34.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire
    with ddtrace v0.45.2, Copyright Datadog, by Datadog
```
- Output of `php -m`
```
[PHP Modules]
bcmath
blackfire
calendar
Core
ctype
curl
date
ddtrace
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
igbinary
imagick
imap
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
blackfire
ddtrace
```

**OS Info**
- Docker image based on `debian:buster-slim` (amd64)
- PHP packages from deb.sury.org

**Output of dd-doctor**
N/A

---

Please let me know how to debug this further.

**Comment by labbati** [comment]
Thanks @Majkl578 let us look into this and we will get back to you. For now we do not need any more info.

**Comment by SammyK** [comment]
Hey @Majkl578! Thanks so much for reporting this. A patch for this issue will be released early next week. Until then, you're welcome to try the nightly build ([.deb](https://165307-119990860-gh.circle-artifacts.com/0/datadog-php-tracer_1.0.0-nightly_amd64.deb)) to verify that the patch fixes the issue. We'll follow up next week when the patch is released.

**Comment by SammyK** [comment]
@Majkl578 We just [released 0.46.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.46.0) which should fix this issue. Would you mind confirming that upgrading fixes the issue on your side? Thanks again for reporting this issue!

**Comment by labbati** [comment]
I am closing this issue for now as the fix has been released. Please feel free to reopen if anything else comes up.

**Comment by Majkl578** [comment]
Thanks both of you, I've not been able to upgrade just yet but I'll certainly let you know whether it fixed my problem! Thank you.

> Please feel free to reopen if anything else comes up.

Unfortunately GitHub doesn't allow issue authors to reopen issues closed by maintainers but not a biggie. :)

**Comment by labbati** [comment]
> Unfortunately GitHub doesn't allow issue authors to reopen issues closed by maintainers but not a biggie. :)

this is a very good point 😄  and we should reword our messages to: "feel free to let us know if anything else will come up and we will immediately reopen the issue".
